Основная разметка
konkoven/technomart pull request #2
Opened 2020-11-08 19:11 UTC by konkoven

Создал разметку без картинок.

2020-11-19 13:21 UTC, VorgSpring requested changes
В общем не плохо, надо убрать теги `br`, по лучше продумать где будут контейнеры, добавить больше классов и внимательнее смотреть на макет)

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <p>ТЕХНОМАРТ</p>
на самом деле это не параграф, это ссылка на главную, но т.к. это и есть главная то ссылка без атрибута `href`

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <button type="submit"></button>
здесь у поиска нет батона

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <h4>Закладки</h4>
не знаю от куда ты это взял, но там такого нету

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <div class="bascket">
не правильно разметил корзину
корзина, закладки и оформить заказ это ссылки, на воображаемые страницы

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <div>
контейнеру нужен класс

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        г. Санкт-Петербург, ул. Б.Конюшенная, д. 19/8</p>
есть специальный тег `address` для таких вещей

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      </ul>
на макете две кнопки: "Войти" и "Регистрация", внимательнее будь. Такая штука в каталоге, и сделана не правильно, кнопки тут не причём

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <nav class="menu">
не корректный класс, это не меню это навигация

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <h1>ТЕХНОМАРТ</h1>
на макете нет этого заголовка, внимательнее смотри макет

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <section class="offers">
не критично, но я бы как то по другому назвал этот класс, оставь так если хочешь

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +          <button type="button">Открыть каталог</button>
это удали пока, потом доделаем слайдер

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        <li>
я бы всё таки добавил классы на `ul` и `li`, причём там где слайдер нужен ещё один класс, потому что он выбивается из сетки

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +          <p>На любой вкус</p>
подумай чем этот список отличается от других, есть несколько вариантов как это можно сделать: один - разметкой, другой стилями, в любом случае нужно поправить

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        <button type="button">ВСЕ ПОПУЛЯРНЫЕ ТОВАРЫ</button>
это не кнопка, это ссылка

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      </div>
популярные товары и популярные производители - один и тот же, по стилям элемент, надо дать и там и там одинаковые классы

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      </div>
написал выше

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        </li>
верстка этого элемента сложнее чем тебе кажется, тут есть фотка и скрытые элементы которые показываются при наведении, посмотри в `styleguide`

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        <li>METABO</li>
все это ссылки на производителей

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <section class="service">
тут не хватает контейнера, подумай почему

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <h2>ДОСТАВКА</h2>
это не `h2`, сам подумай у тебя блок "Сервисы" - это второй уровень.

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <p>Хороший интернет-магазин отличается от плохого не только ценами!<br>
тег `br` очень коварный, его нужно ставить только в экстренных случаях, это не тот случай для этого тега

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      </ul>
вот здесь как раз это кнопки, потому что это слайдер

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <h2>ДОСТАВКА</h2>
не хватает блока с текстом

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +  <header>
хедеру нужен класс

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +  <footer>
футеру нужен класс

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    </div>
здесь все как в хедере

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <section class="information">
здесь у тебя два контейнера с описанием и контактами

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <p>Мы можем доставить ваш товар в самые отдаленные точки России!<br>
`br` надо убрать

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +      <p>Вы можете забрать товар сами,<br>
`br` надо убрать

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        +7 (812) 555-05-55
телефон это ссылка формата
`<a href="tel:+78125550555">+7 (812) 555-05-55</a>`

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +    <div class="item">
а почему это не навигация?

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +        <li><a href="#">Каталог</a></li>
ссылку правильную нужно, на каталог

2020-11-19 13:21 UTC, VorgSpring commented on index.html
> +  </footer>
в футоре нужно добавить контейнеров, внимательнее посмотри на макет

2020-11-20 10:04 UTC, konkoven commented on index.html
> +    <h1>ТЕХНОМАРТ</h1>
скрытый заголовок для читалок

2020-11-20 18:21 UTC, VorgSpring requested changes

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +      <div class="description">
`p` сам по себе блочный и его не надо оборачивать в `div`

2020-11-20 18:21 UTC, VorgSpring commented on index.html
>      <div>
`nav` не надо оборачивать в `div`, нам здесь хватает обёрток

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +      <nav class="menu">
и класс "menu" надо все-таки поменять, потому что это не меню это навигация

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +              <p class="appendix">На любой вкус</p>
это все таки ссылки 
![styleguide](https://user-images.githubusercontent.com/16783786/99830105-49d49e80-2b6e-11eb-809e-46d39d9c17bd.jpg)

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +                <h2>Дрели</h2>
не согласен что это `h2` - это все таки `h3`

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +                <p class="navigate-left">&lt;</p>
а это кнопки а не параграфы

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +              </div>
не хватает ещё одной навигации в виде кружочков 
![Inkedtechnomart-index_LI](https://user-images.githubusercontent.com/16783786/99830682-19d9cb00-2b6f-11eb-9567-6aed7f594cd3.jpg)

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +          BFG 9000">
лишний перенос

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +        <article>
забыл про скрытые элементы
![styleguide](https://user-images.githubusercontent.com/16783786/99831058-97054000-2b6f-11eb-8787-bf1cf5c13687.jpg)

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +      <section class="offers">
тогда уж давай везде ставить скрытые заголовки
`<h2 class="hidden">Предложения</h2>`

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +                <a class="fill-red" href="catalog.html">Открыть каталог</a>
надо вынести из компонента слайдера

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +              <div class="navigate-left-right">
лучше назвать класс 'slider-navigate'

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +            <div class="fill-green">
здесь `div` не нужен нам хватит `li` как контейнера на этот элемент

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +          <p class="prize">15500 Р.</p>
```  
<del class="original-prize">22500 Р.</del>
<span class="prize">15500 Р.</span>
```

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +      <div class="services">
не хватает ещё контейнера

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +        <p>Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для ремонта и строительства не оставит
надо классы дать параграфам

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +        <ul>
этому тоже классы

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +        <a href="#">Заблудились? Напишите нам!</a>
это кнопка

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +        <a href="#">Подробнее о компании</a>
ссылкам надо везде дать один класс

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +    <div class="up">
надо переименовать в более понятный класс

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +  <footer class="down">
надо переименовать класс, по примеру `header` можно назвать "main-footer"

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +    <div class="navigation">
я бы назвал "footer-navigation" и и `div` нам хватит `nav`

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +    <div class="item-menu">
это все таки навигация, класс надо переименовать и тег поменять

2020-11-20 18:21 UTC, VorgSpring commented on index.html
> +    <div class="container">
не хватает ещё одного контейнера для фона либо вверху, либо внизу

2020-11-20 18:21 UTC, VorgSpring commented on index.html
>    </footer>
футер надо переделать чутка вот тебе подсказка
![Безымянный](https://user-images.githubusercontent.com/16783786/99835894-53620480-2b76-11eb-8678-5656d95a06e2.jpg)

2020-11-22 12:12 UTC, konkoven commented on index.html
> +            <div class="fill-green">
тогда везде нужно будет убрать дивы в этом списке?

2020-11-22 12:14 UTC, konkoven commented on index.html
> +        <article>
не, не забыл не знаю, как это нужно сделать. Разметку могу вставить.

2020-11-22 15:44 UTC, VorgSpring requested changes
не все поправил

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +            <div class="fill-green">
да

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +      <div class="copyright">
форматирование слетело

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +        <p>Обратная связь:
на следующую строку перенеси, как в следующем `p`, чтобы одинаково было везде

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +      <div class="social">
здесь `div` не нужен нам хватит `ul` как контейнера

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +      <div class="down-fill">
не нужен здесь контейнер, т.к. у нас уже есть верхний контейнер перетрет фон футора

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +    <div class="high-fill">
предлагаю вот так назвать этот класс "upper-header" или "header-wrapper"

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +              </nav>
там нет списка и это кнопки, они будут с позиционированы специально, засунь их вместе со стрелочками

2020-11-22 15:44 UTC, VorgSpring commented on index.html
> +              <a class="fill-red" href="catalog.html">Открыть каталог</a>
этот элемент одинаковый для всех элементов слайдера, надо его вынести от сюда

2020-12-01 17:16 UTC, VorgSpring requested changes

2020-12-01 17:16 UTC, VorgSpring commented on index.html
>            <li class="materials">
не корректно ты назвал класс, у тебя же они одинаковые по структуре, тут нужно два класса, один который характеризует общую структуру, а другой различея, к примеру можно так `offer-item offer-materials` и у всех так

2020-12-01 17:16 UTC, VorgSpring commented on index.html
>            <p><del class="original-prize">32500 Р.</del></p>
`p` не нужен

2020-12-01 17:16 UTC, VorgSpring commented on index.html
> +          <li class="slider-drill-box">
слайдер все равно не правильно сделал)) давай пока не будем его мучить, оставим пустой
`<div class="slider-offers"></div>`

2020-12-01 17:16 UTC, VorgSpring commented on index.html
> +            <p class="appendix">На любой вкус</p>
appendix это смешно конечно

2020-12-01 17:20 UTC, VorgSpring requested changes

2020-12-01 17:20 UTC, VorgSpring commented on index.html
> +            <div class="notice">new</div>
это скорее `span`

2020-12-01 17:32 UTC, VorgSpring requested changes

2020-12-01 17:32 UTC, VorgSpring commented on index.html
> +    <div class="offers-items">
`offers-container`

2020-12-01 17:32 UTC, VorgSpring commented on index.html
> +        <ul class="colors-palette">
`offers-items`

2020-12-01 17:32 UTC, VorgSpring commented on index.html
> +          <p><del class="original-prize">30500 Р.</del></p>
здесь тоже не убрал `p`

2020-12-01 17:32 UTC, VorgSpring commented on index.html
> +          <p class="prize">12500 Р.</p>
`span`

2020-12-15 09:46 UTC, VorgSpring requested changes
нужно форматирование поправить и ты снова не все поправил с прошлого ревью

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +            <div class="upper-fill"></div>
не нужный элемент, у тебя header такой-же как на главной, только корзина и пользователь отличаются

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                <div>
div не нужен

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                    <a class="person" href="">Равшан Джамшутович</a>
там у тебя ещё элементы есть
![styleguide](https://user-images.githubusercontent.com/16783786/102196107-7e6b1a00-3ed0-11eb-8041-cbb9e7ab2cf8.jpg)

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                    <a class="my_orders" href="">Мои заказы</a>
я бы все таки вот так разделил
![styleguide](https://user-images.githubusercontent.com/16783786/102196226-a78baa80-3ed0-11eb-86e7-32d805ee64af.jpg)

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +        <div class="main-container">
для чего тебе этот контейнер?
тебе нужен вот такой контейнер, а так он у тебя на весь main
![technomart-catalog](https://user-images.githubusercontent.com/16783786/102197238-e79f5d00-3ed1-11eb-8b29-a4507f79897c.jpg)

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                        BOSCH
это нужно в `lebel` обернуть и сделать во всех подобных местах

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                        </p>
это один параграф

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                    <button type="button">следующая</button>
это ссылки и их список

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                </div>
это список

2020-12-15 09:46 UTC, VorgSpring commented on catalog.html
> +                </div>
это тоже список
и тут ссылки а не `img`

2020-12-15 17:55 UTC, VorgSpring requested changes

2020-12-15 17:55 UTC, VorgSpring commented on catalog.html
> +            </div>
`div` не нужен

2020-12-15 17:55 UTC, VorgSpring commented on catalog.html
> +                <hr>
нужно убрать, они не нужны

2020-12-15 17:55 UTC, VorgSpring commented on catalog.html
> +                </div>
пока этот элемент оставим пустым тегом

2021-01-11 16:15 UTC, VorgSpring requested changes
ругается валидатор
index.html
![image](https://user-images.githubusercontent.com/16783786/104199423-7a330d80-5438-11eb-9f96-53a03d9bad4d.png)

catalog.html
![image](https://user-images.githubusercontent.com/16783786/104199598-aea6c980-5438-11eb-8532-6098305ee4b4.png)

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +              Корзина
здесь другой текст, посмотри макет

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +              Закладки
здесь другой текст, посмотри макет

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +              ТЕХНОМАРТ
текст в верхнем регистре через css сделаем, поставь в нижнем

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +              <input type="text" placeholder="Поиск">
здесь другой текст у placeholder , посмотри макет

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </a>
давай закладки, корзину и оформить заказ положим в div

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +                </div>
description, contacts и person-corner надо в div обернуть

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +                <div class="person-corner-links"></div>
повнимательнее, здесь div закрылся и линки не в диве

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +
с форматированием по аккуратнее

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +                        </li>
классы у этих li в навигации должны быть одинаковые, там же одинаковые стили

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            <ul>
там ещё есть значок "домой" который ведёт на главную

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +        </div>
div не нужен
и это h1

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +
форматирование!

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </span>
это не span это заголовок

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +        <div class="filters-column">
давай более семантично сделаем блок фильтров тегом `section`

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </span>
это относиться к блоку с ценой, который мы с тобой решили пока сделать пустым

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </div>
это не понимаю что такое))

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </div>
хоть он у нас и пустой, но всё-же это часть формы

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </form>
тут форма одна на все фильтры

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +        <div class="sorting">
нужно sorting, item-cards и pages положить в `section`

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +            </span>
это заголовок

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +
поправь отступы, везде, с форматированием аккуратнее надо быть

2021-01-11 16:15 UTC, VorgSpring commented on catalog.html
> +                <div class="explainer-box">
это у нас уже class='container'

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +        </a>
тоже самое что и на верху

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +        </li>
все тоже самое что и в каталоге

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +        Предложения
отступ нужен ещё

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +            </h3>
чёт тут много материалов

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +            <a href="#">Инструмент</a>
здесь тоже ссылка не нужна)) во всех подобных элементах надо убрать

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +    <div class="offers-container">
здесь контейнер не нужен нам

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +            </span>
дублирующие блоки не нужны, убери везде

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +      <div class="services-box-cotainer">
у нас уже есть class='container'

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +        <a class="long-red-btn" href="catalog.html">
наверное все таки ссылка не каталог ведёт

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +      </div>
ПОПУЛЯРНЫЕ ТОВАРЫ и ПОПУЛЯРНЫЕ ПРОИЗВОДИТЕЛИ одинаковые по стилю блоки, давай и класс им тоже одинаковые дадим

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +          ПОПУЛЯРНЫЕ ТОВАРЫ
Везде по коду нужно убрать текст в верхнем регистре

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +        </div>
все равно не правильная разметка слайдера)) давай все таки его пока пустым оставим

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +          <a href="htmlacademy.ru">
надо полный адрес прописать

2021-01-11 16:15 UTC, VorgSpring commented on index.html
> +      <div class="container">
контейнер должен навигацию тоже захватить, посмотри внимательнее на подсказку в последнем комментарии

2021-01-17 17:33 UTC, VorgSpring requested changes

2021-01-17 17:33 UTC, VorgSpring commented on catalog.html
> +        </div>
Отправил код в телегу для всего этого блока

2021-01-17 17:33 UTC, VorgSpring commented on catalog.html
> +                        </div>
Отправил код в телегу для всего этого блока

2021-01-17 17:33 UTC, VorgSpring commented on catalog.html
> +                        </article>
заменить на нормальный

2021-01-17 17:33 UTC, VorgSpring commented on catalog.html
> +    </footer>
Отправил код в телегу для всего этого блока

2021-01-17 17:33 UTC, VorgSpring commented on index.html
> +    </nav>
Отправил код в телегу для всего этого блока

2021-01-17 17:33 UTC, VorgSpring commented on index.html
> +            <a href="#">Материалы</a>
удалить

2021-01-17 17:33 UTC, VorgSpring commented on index.html
> +  </footer>
Отправил код в телегу для всего этого блока

2021-01-19 18:15 UTC, merged